// <auto-generated />
namespace ModernWebStore.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstmigrationaddedimagecolumnatproducttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmigrationaddedimagecolumnatproducttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701210606321_first-migration-added-image-column-at-product-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
